module.exports.config = {
  name: "beo",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "NQH VIP",
  description: "Random Ảnh Beo Xinh Gái Cực Bổ Mắt UwU",
  commandCategory: "Random-img",
  usages: "beo",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
};

module.exports.run = async({api,event,args,client,Users,Threads,__GLOBAL,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
  var link = [
"https://i.imgur.com/q4tqlph.jpeg",
"https://i.imgur.com/4bWMKbY.jpeg",
"https://i.imgur.com/p6Ny8Mg.jpeg",
"https://i.imgur.com/dzSklSP.jpeg",
"https://i.imgur.com/Bpf2q5Y.jpeg",
"https://i.imgur.com/n5JTrTG.jpeg",
"https://i.imgur.com/Nvcbv7r.jpeg",
"https://i.imgur.com/oNp1Mar.jpeg",
"https://i.imgur.com/I0ovR7g.jpeg",
"https://i.imgur.com/TAn0QFN.jpeg",
"https://i.imgur.com/S0uzL6x.jpeg",
"https://i.imgur.com/AKz1QBT.jpeg",
"https://i.imgur.com/9AqSFYW.jpeg",
"https://i.imgur.com/kXHJ36p.jpeg",
 "https://i.imgur.com/S32GtDV.jpeg",
 "https://i.imgur.com/nbgOkbT.jpeg",
 "https://i.imgur.com/qloKmzE.jpeg",
 "https://i.imgur.com/P6luIpI.jpeg",
 "https://i.imgur.com/0OtDczY.jpeg",
 "https://i.imgur.com/M8lOcDT.jpeg",
 "https://i.imgur.com/rj0BA1E.jpeg",
 "https://i.imgur.com/rXe6vIQ.jpeg",
 "https://i.imgur.com/nbgiPPU.jpeg",
 "https://i.imgur.com/ydqBeuH.jpeg",
 "https://i.imgur.com/lMhKEA9.jpeg",
 "https://i.imgur.com/VymJBRh.jpeg",
 "https://i.imgur.com/dxDbN6R.jpeg",
 "https://i.imgur.com/FnrfUTO.jpeg",
 "https://i.imgur.com/uuexcX3.jpeg",
 "https://i.imgur.com/m7a8Uix.jpeg",
 "https://i.imgur.com/j0TqFCW.jpeg",
 "https://i.imgur.com/LQAvTzS.jpeg",
 "https://i.imgur.com/NaCRCRk.jpeg",
 "https://i.imgur.com/gUu97qV.jpeg",
 "https://i.imgur.com/1i57S5M.jpeg",
 "https://i.imgur.com/K6WNC2C.jpeg",
 "https://i.imgur.com/Fw1OzLd.jpeg",
 "https://i.imgur.com/xeJbwfd.jpeg",
 "https://i.imgur.com/TiGTpO6.jpeg",
 "https://i.imgur.com/THHFKJ2.jpeg",
 "https://i.imgur.com/eDTVNEs.jpeg",
 "https://i.imgur.com/2MmRl1p.jpeg",
 "https://i.imgur.com/4W1RTJg.jpeg",
 "https://i.imgur.com/j3aExXX.jpeg",
 "https://i.imgur.com/dK4tAsg.jpeg",
 "https://i.imgur.com/LrGbHbv.jpeg",
 "https://i.imgur.com/7ga2f3q.jpeg",
 "https://i.imgur.com/65UqGiq.jpeg",
 "https://i.imgur.com/ujFbvWU.jpeg",
 "https://i.imgur.com/wEQKqem.jpeg",
 "https://i.imgur.com/O8J60su.jpeg",
 "https://i.imgur.com/n2VD6VM.jpeg",
 "https://i.imgur.com/WAY7Vgk.jpeg",
 "https://i.imgur.com/uANsKLI.jpeg",   
 "https://i.imgur.com/6yPX5kK.jpeg",
 "https://i.imgur.com/wBUq3bN.jpeg",
 "https://i.imgur.com/apxh8c8.jpeg",
 "https://i.imgur.com/LIREc4R.jpeg",
 "https://i.imgur.com/TdaxxAU.jpeg",
 "https://i.imgur.com/Rbv45MA.jpeg",
 "https://i.imgur.com/5olEDze.jpeg",
 "https://i.imgur.com/jI4HCMX.jpeg",
 "https://i.imgur.com/9Tl5otU.jpeg",
 "https://i.imgur.com/mZlxHld.jpeg",
 "https://i.imgur.com/6CgUQlT.jpeg",
 "https://i.imgur.com/mdgG9XL.jpeg",
 "https://i.imgur.com/HiSI7IM.jpeg",
 "https://i.imgur.com/CL71HrZ.jpeg",
 "https://i.imgur.com/pbdmEuB.jpeg",
 "https://i.imgur.com/lYg3RnK.jpeg",
 "https://i.imgur.com/ky1OVcq.jpeg",
 "https://i.imgur.com/XF3qGBE.jpeg",   
 "https://i.imgur.com/TPx2DV6.jpeg",
 "https://i.imgur.com/PxtA4nz.jpeg",
 "https://i.imgur.com/GmFop1e.jpeg",
 "https://i.imgur.com/qv03rCc.jpeg",
 "https://i.imgur.com/YNevD0g.jpeg",
 "https://i.imgur.com/m0a3scO.jpeg",
 "https://i.imgur.com/noy4UWO.jpeg",
 "https://i.imgur.com/MpPXkOP.jpeg",
 "https://i.imgur.com/TFgNT0t.jpeg",
 "https://i.imgur.com/ihEZ47d.jpeg",
 "https://i.imgur.com/qqgCkml.jpeg",
 "https://i.imgur.com/xnQSjwa.jpeg",
 "https://i.imgur.com/olLF47I.jpeg",
 "https://i.imgur.com/UVoWNus.jpeg",
 "https://i.imgur.com/6YbHVN9.jpeg",
 "https://i.imgur.com/P3iuHvy.jpeg",
 "https://i.imgur.com/h14C73O.jpeg",
 "https://i.imgur.com/sBM7eA1.jpeg",
 "https://i.imgur.com/MBQdSdY.jpeg",
 "https://i.imgur.com/cs1HPpH.jpeg",
 "https://i.imgur.com/exrLo9g.jpeg",
 "https://i.imgur.com/2HyGDqv.jpeg",
 "https://i.imgur.com/wy8ToOn.jpeg",
 "https://i.imgur.com/JGjwcRe.jpeg",
 "https://i.imgur.com/lRhUWhO.jpeg",
 "https://i.imgur.com/sMe1BWL.jpeg",
 "https://i.imgur.com/7jHwX3p.jpeg",
 "https://i.imgur.com/IWFgqi8.jpeg",
 "https://i.imgur.com/lkmfUq4.jpeg",
 "https://i.imgur.com/JlBiwne.jpeg",
 "https://i.imgur.com/S3MI8ps.jpeg",
 "https://i.imgur.com/WIkXY47.jpeg",
 "https://i.imgur.com/qBoX2PT.jpeg",
 "https://i.imgur.com/QImHQgz.jpeg",
 "https://i.imgur.com/MVq9iDh.jpeg",
 "https://i.imgur.com/Yri2zzK.jpeg",
 "https://i.imgur.com/rtb1Wos.jpeg",
 "https://i.imgur.com/XF1HkwS.jpeg",
 "https://i.imgur.com/DDsnG44.jpeg",
 "https://i.imgur.com/OGfIcDi.jpeg",
 "https://i.imgur.com/bAtvtoW.jpeg",
 "https://i.imgur.com/h3yvhMJ.jpeg",
 "https://i.imgur.com/4uZW7Eh.jpeg",
 "https://i.imgur.com/xLilRJF.jpeg",
 "https://i.imgur.com/clb7dxL.jpeg",   
  ];
  var max = Math.floor(Math.random() * 6);  
  var min = Math.floor(Math.random() * 2);
  var data = await Currencies.getData(event.senderID);
  var exp =  data.exp;
  var money = data.money
      if(money < 100000) api.sendMessage("𝐌𝐚̀𝐲 𝐩𝐡𝐚̉𝐢 𝐜𝐨́ đ𝐮̉ 100000 đ𝐨̂ đ𝐞̂̉ 𝐱𝐞𝐦 𝐚̉𝐧𝐡 ?",event.threadID,event.messageID)
          else {
   Currencies.setData(event.senderID, options = {money: money - 100000})
   var callback = () => api.sendMessage({body:`𝐀̉𝐧𝐡 𝐁𝐞𝐨 𝐝𝐞̂̃ 𝐭𝐡𝐮̛𝐨̛𝐧𝐠 𝐜𝐮̉𝐚 𝐦𝐚̀𝐲 𝐧𝐞̀ 𝐔𝐰𝐔\n🔥 𝐂𝐡𝐨 𝐭𝐚𝐨 𝐱𝐢𝐧 𝐧𝐡𝐨́ 😎: -100000 đô 🔥`,attachment: fs.createReadStream(__dirname + "/cache/5.jpeg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/5.jpeg")); 
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/5.jpeg")).on("close",() => callback());
   }
};